{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "druid.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "delete", "create"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "druid.fullname" . }}
  labels:
    {{- include "druid.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ include "druid.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
