apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "postgresql.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
